# Generated by Django 5.2 on 2025-06-14 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_missing_elements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(verbose_name='Расстояние (км)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='place1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_routes', to='catalog.place'),
        ),
        migrations.AlterField(
            model_name='route',
            name='place2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_routes', to='catalog.place'),
        ),
        migrations.AlterField(
            model_name='route',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='route',
            name='transport',
            field=models.CharField(choices=[('walk', 'Пешком'), ('bus', 'Автобус'), ('trolley', 'Троллейбус'), ('taxi', 'Такси')], default='walk', max_length=100, verbose_name='Транспорт'),
        ),
    ]
